version: "2"

setup:
  go: "1.24"

run:
  concurrency: 8
  timeout: 10m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - revive
    - unused
    - staticcheck
  disable:
    - wsl

linters-settings:
  govet:
    check-shadowing: true
    enable:
      - loopclosure
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  exclude:
    - "G104"  # Игнорирование ошибок
    - 'exported func .* returns unexported type .*'
    - 'don\t use an underscore in package name'
  exclude-files:
    - '.*\.pb\.go$'
    - '.*\.pb\.gw\.go$'
  exclude-dirs:
    - bin
    - vendor
    - .git