// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/ecommerc-go/users/internal/service.UserService -o user_service_minimock.go -n UserServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/ecommerc-go/users/internal/models"
	"github.com/gojuno/minimock/v3"
)

// UserServiceMock implements mm_service.UserService
type UserServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteProfile          func(ctx context.Context, id string) (err error)
	funcDeleteProfileOrigin    string
	inspectFuncDeleteProfile   func(ctx context.Context, id string)
	afterDeleteProfileCounter  uint64
	beforeDeleteProfileCounter uint64
	DeleteProfileMock          mUserServiceMockDeleteProfile

	funcGetProfile          func(ctx context.Context, id string) (up1 *models.UserProfile, err error)
	funcGetProfileOrigin    string
	inspectFuncGetProfile   func(ctx context.Context, id string)
	afterGetProfileCounter  uint64
	beforeGetProfileCounter uint64
	GetProfileMock          mUserServiceMockGetProfile

	funcLoginUser          func(ctx context.Context, req *models.LoginUserRequest) (s1 string, err error)
	funcLoginUserOrigin    string
	inspectFuncLoginUser   func(ctx context.Context, req *models.LoginUserRequest)
	afterLoginUserCounter  uint64
	beforeLoginUserCounter uint64
	LoginUserMock          mUserServiceMockLoginUser

	funcRegisterUser          func(ctx context.Context, req *models.RegisterRequest) (s1 string, err error)
	funcRegisterUserOrigin    string
	inspectFuncRegisterUser   func(ctx context.Context, req *models.RegisterRequest)
	afterRegisterUserCounter  uint64
	beforeRegisterUserCounter uint64
	RegisterUserMock          mUserServiceMockRegisterUser

	funcUpdateProfile          func(ctx context.Context, req *models.UpdateProfileRequest) (err error)
	funcUpdateProfileOrigin    string
	inspectFuncUpdateProfile   func(ctx context.Context, req *models.UpdateProfileRequest)
	afterUpdateProfileCounter  uint64
	beforeUpdateProfileCounter uint64
	UpdateProfileMock          mUserServiceMockUpdateProfile
}

// NewUserServiceMock returns a mock for mm_service.UserService
func NewUserServiceMock(t minimock.Tester) *UserServiceMock {
	m := &UserServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteProfileMock = mUserServiceMockDeleteProfile{mock: m}
	m.DeleteProfileMock.callArgs = []*UserServiceMockDeleteProfileParams{}

	m.GetProfileMock = mUserServiceMockGetProfile{mock: m}
	m.GetProfileMock.callArgs = []*UserServiceMockGetProfileParams{}

	m.LoginUserMock = mUserServiceMockLoginUser{mock: m}
	m.LoginUserMock.callArgs = []*UserServiceMockLoginUserParams{}

	m.RegisterUserMock = mUserServiceMockRegisterUser{mock: m}
	m.RegisterUserMock.callArgs = []*UserServiceMockRegisterUserParams{}

	m.UpdateProfileMock = mUserServiceMockUpdateProfile{mock: m}
	m.UpdateProfileMock.callArgs = []*UserServiceMockUpdateProfileParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserServiceMockDeleteProfile struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockDeleteProfileExpectation
	expectations       []*UserServiceMockDeleteProfileExpectation

	callArgs []*UserServiceMockDeleteProfileParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockDeleteProfileExpectation specifies expectation struct of the UserService.DeleteProfile
type UserServiceMockDeleteProfileExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockDeleteProfileParams
	paramPtrs          *UserServiceMockDeleteProfileParamPtrs
	expectationOrigins UserServiceMockDeleteProfileExpectationOrigins
	results            *UserServiceMockDeleteProfileResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockDeleteProfileParams contains parameters of the UserService.DeleteProfile
type UserServiceMockDeleteProfileParams struct {
	ctx context.Context
	id  string
}

// UserServiceMockDeleteProfileParamPtrs contains pointers to parameters of the UserService.DeleteProfile
type UserServiceMockDeleteProfileParamPtrs struct {
	ctx *context.Context
	id  *string
}

// UserServiceMockDeleteProfileResults contains results of the UserService.DeleteProfile
type UserServiceMockDeleteProfileResults struct {
	err error
}

// UserServiceMockDeleteProfileOrigins contains origins of expectations of the UserService.DeleteProfile
type UserServiceMockDeleteProfileExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Optional() *mUserServiceMockDeleteProfile {
	mmDeleteProfile.optional = true
	return mmDeleteProfile
}

// Expect sets up expected params for UserService.DeleteProfile
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Expect(ctx context.Context, id string) *mUserServiceMockDeleteProfile {
	if mmDeleteProfile.mock.funcDeleteProfile != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Set")
	}

	if mmDeleteProfile.defaultExpectation == nil {
		mmDeleteProfile.defaultExpectation = &UserServiceMockDeleteProfileExpectation{}
	}

	if mmDeleteProfile.defaultExpectation.paramPtrs != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by ExpectParams functions")
	}

	mmDeleteProfile.defaultExpectation.params = &UserServiceMockDeleteProfileParams{ctx, id}
	mmDeleteProfile.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteProfile.expectations {
		if minimock.Equal(e.params, mmDeleteProfile.defaultExpectation.params) {
			mmDeleteProfile.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteProfile.defaultExpectation.params)
		}
	}

	return mmDeleteProfile
}

// ExpectCtxParam1 sets up expected param ctx for UserService.DeleteProfile
func (mmDeleteProfile *mUserServiceMockDeleteProfile) ExpectCtxParam1(ctx context.Context) *mUserServiceMockDeleteProfile {
	if mmDeleteProfile.mock.funcDeleteProfile != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Set")
	}

	if mmDeleteProfile.defaultExpectation == nil {
		mmDeleteProfile.defaultExpectation = &UserServiceMockDeleteProfileExpectation{}
	}

	if mmDeleteProfile.defaultExpectation.params != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Expect")
	}

	if mmDeleteProfile.defaultExpectation.paramPtrs == nil {
		mmDeleteProfile.defaultExpectation.paramPtrs = &UserServiceMockDeleteProfileParamPtrs{}
	}
	mmDeleteProfile.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteProfile.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteProfile
}

// ExpectIdParam2 sets up expected param id for UserService.DeleteProfile
func (mmDeleteProfile *mUserServiceMockDeleteProfile) ExpectIdParam2(id string) *mUserServiceMockDeleteProfile {
	if mmDeleteProfile.mock.funcDeleteProfile != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Set")
	}

	if mmDeleteProfile.defaultExpectation == nil {
		mmDeleteProfile.defaultExpectation = &UserServiceMockDeleteProfileExpectation{}
	}

	if mmDeleteProfile.defaultExpectation.params != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Expect")
	}

	if mmDeleteProfile.defaultExpectation.paramPtrs == nil {
		mmDeleteProfile.defaultExpectation.paramPtrs = &UserServiceMockDeleteProfileParamPtrs{}
	}
	mmDeleteProfile.defaultExpectation.paramPtrs.id = &id
	mmDeleteProfile.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDeleteProfile
}

// Inspect accepts an inspector function that has same arguments as the UserService.DeleteProfile
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Inspect(f func(ctx context.Context, id string)) *mUserServiceMockDeleteProfile {
	if mmDeleteProfile.mock.inspectFuncDeleteProfile != nil {
		mmDeleteProfile.mock.t.Fatalf("Inspect function is already set for UserServiceMock.DeleteProfile")
	}

	mmDeleteProfile.mock.inspectFuncDeleteProfile = f

	return mmDeleteProfile
}

// Return sets up results that will be returned by UserService.DeleteProfile
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Return(err error) *UserServiceMock {
	if mmDeleteProfile.mock.funcDeleteProfile != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Set")
	}

	if mmDeleteProfile.defaultExpectation == nil {
		mmDeleteProfile.defaultExpectation = &UserServiceMockDeleteProfileExpectation{mock: mmDeleteProfile.mock}
	}
	mmDeleteProfile.defaultExpectation.results = &UserServiceMockDeleteProfileResults{err}
	mmDeleteProfile.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteProfile.mock
}

// Set uses given function f to mock the UserService.DeleteProfile method
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Set(f func(ctx context.Context, id string) (err error)) *UserServiceMock {
	if mmDeleteProfile.defaultExpectation != nil {
		mmDeleteProfile.mock.t.Fatalf("Default expectation is already set for the UserService.DeleteProfile method")
	}

	if len(mmDeleteProfile.expectations) > 0 {
		mmDeleteProfile.mock.t.Fatalf("Some expectations are already set for the UserService.DeleteProfile method")
	}

	mmDeleteProfile.mock.funcDeleteProfile = f
	mmDeleteProfile.mock.funcDeleteProfileOrigin = minimock.CallerInfo(1)
	return mmDeleteProfile.mock
}

// When sets expectation for the UserService.DeleteProfile which will trigger the result defined by the following
// Then helper
func (mmDeleteProfile *mUserServiceMockDeleteProfile) When(ctx context.Context, id string) *UserServiceMockDeleteProfileExpectation {
	if mmDeleteProfile.mock.funcDeleteProfile != nil {
		mmDeleteProfile.mock.t.Fatalf("UserServiceMock.DeleteProfile mock is already set by Set")
	}

	expectation := &UserServiceMockDeleteProfileExpectation{
		mock:               mmDeleteProfile.mock,
		params:             &UserServiceMockDeleteProfileParams{ctx, id},
		expectationOrigins: UserServiceMockDeleteProfileExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteProfile.expectations = append(mmDeleteProfile.expectations, expectation)
	return expectation
}

// Then sets up UserService.DeleteProfile return parameters for the expectation previously defined by the When method
func (e *UserServiceMockDeleteProfileExpectation) Then(err error) *UserServiceMock {
	e.results = &UserServiceMockDeleteProfileResults{err}
	return e.mock
}

// Times sets number of times UserService.DeleteProfile should be invoked
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Times(n uint64) *mUserServiceMockDeleteProfile {
	if n == 0 {
		mmDeleteProfile.mock.t.Fatalf("Times of UserServiceMock.DeleteProfile mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteProfile.expectedInvocations, n)
	mmDeleteProfile.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteProfile
}

func (mmDeleteProfile *mUserServiceMockDeleteProfile) invocationsDone() bool {
	if len(mmDeleteProfile.expectations) == 0 && mmDeleteProfile.defaultExpectation == nil && mmDeleteProfile.mock.funcDeleteProfile == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteProfile.mock.afterDeleteProfileCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteProfile.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteProfile implements mm_service.UserService
func (mmDeleteProfile *UserServiceMock) DeleteProfile(ctx context.Context, id string) (err error) {
	mm_atomic.AddUint64(&mmDeleteProfile.beforeDeleteProfileCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteProfile.afterDeleteProfileCounter, 1)

	mmDeleteProfile.t.Helper()

	if mmDeleteProfile.inspectFuncDeleteProfile != nil {
		mmDeleteProfile.inspectFuncDeleteProfile(ctx, id)
	}

	mm_params := UserServiceMockDeleteProfileParams{ctx, id}

	// Record call args
	mmDeleteProfile.DeleteProfileMock.mutex.Lock()
	mmDeleteProfile.DeleteProfileMock.callArgs = append(mmDeleteProfile.DeleteProfileMock.callArgs, &mm_params)
	mmDeleteProfile.DeleteProfileMock.mutex.Unlock()

	for _, e := range mmDeleteProfile.DeleteProfileMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteProfile.DeleteProfileMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteProfile.DeleteProfileMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteProfile.DeleteProfileMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteProfile.DeleteProfileMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockDeleteProfileParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteProfile.t.Errorf("UserServiceMock.DeleteProfile got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteProfile.DeleteProfileMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDeleteProfile.t.Errorf("UserServiceMock.DeleteProfile got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteProfile.DeleteProfileMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteProfile.t.Errorf("UserServiceMock.DeleteProfile got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteProfile.DeleteProfileMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteProfile.DeleteProfileMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteProfile.t.Fatal("No results are set for the UserServiceMock.DeleteProfile")
		}
		return (*mm_results).err
	}
	if mmDeleteProfile.funcDeleteProfile != nil {
		return mmDeleteProfile.funcDeleteProfile(ctx, id)
	}
	mmDeleteProfile.t.Fatalf("Unexpected call to UserServiceMock.DeleteProfile. %v %v", ctx, id)
	return
}

// DeleteProfileAfterCounter returns a count of finished UserServiceMock.DeleteProfile invocations
func (mmDeleteProfile *UserServiceMock) DeleteProfileAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteProfile.afterDeleteProfileCounter)
}

// DeleteProfileBeforeCounter returns a count of UserServiceMock.DeleteProfile invocations
func (mmDeleteProfile *UserServiceMock) DeleteProfileBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteProfile.beforeDeleteProfileCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.DeleteProfile.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteProfile *mUserServiceMockDeleteProfile) Calls() []*UserServiceMockDeleteProfileParams {
	mmDeleteProfile.mutex.RLock()

	argCopy := make([]*UserServiceMockDeleteProfileParams, len(mmDeleteProfile.callArgs))
	copy(argCopy, mmDeleteProfile.callArgs)

	mmDeleteProfile.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteProfileDone returns true if the count of the DeleteProfile invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockDeleteProfileDone() bool {
	if m.DeleteProfileMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteProfileMock.invocationsDone()
}

// MinimockDeleteProfileInspect logs each unmet expectation
func (m *UserServiceMock) MinimockDeleteProfileInspect() {
	for _, e := range m.DeleteProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.DeleteProfile at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteProfileCounter := mm_atomic.LoadUint64(&m.afterDeleteProfileCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteProfileMock.defaultExpectation != nil && afterDeleteProfileCounter < 1 {
		if m.DeleteProfileMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.DeleteProfile at\n%s", m.DeleteProfileMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.DeleteProfile at\n%s with params: %#v", m.DeleteProfileMock.defaultExpectation.expectationOrigins.origin, *m.DeleteProfileMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteProfile != nil && afterDeleteProfileCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.DeleteProfile at\n%s", m.funcDeleteProfileOrigin)
	}

	if !m.DeleteProfileMock.invocationsDone() && afterDeleteProfileCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.DeleteProfile at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteProfileMock.expectedInvocations), m.DeleteProfileMock.expectedInvocationsOrigin, afterDeleteProfileCounter)
	}
}

type mUserServiceMockGetProfile struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockGetProfileExpectation
	expectations       []*UserServiceMockGetProfileExpectation

	callArgs []*UserServiceMockGetProfileParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockGetProfileExpectation specifies expectation struct of the UserService.GetProfile
type UserServiceMockGetProfileExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockGetProfileParams
	paramPtrs          *UserServiceMockGetProfileParamPtrs
	expectationOrigins UserServiceMockGetProfileExpectationOrigins
	results            *UserServiceMockGetProfileResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockGetProfileParams contains parameters of the UserService.GetProfile
type UserServiceMockGetProfileParams struct {
	ctx context.Context
	id  string
}

// UserServiceMockGetProfileParamPtrs contains pointers to parameters of the UserService.GetProfile
type UserServiceMockGetProfileParamPtrs struct {
	ctx *context.Context
	id  *string
}

// UserServiceMockGetProfileResults contains results of the UserService.GetProfile
type UserServiceMockGetProfileResults struct {
	up1 *models.UserProfile
	err error
}

// UserServiceMockGetProfileOrigins contains origins of expectations of the UserService.GetProfile
type UserServiceMockGetProfileExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProfile *mUserServiceMockGetProfile) Optional() *mUserServiceMockGetProfile {
	mmGetProfile.optional = true
	return mmGetProfile
}

// Expect sets up expected params for UserService.GetProfile
func (mmGetProfile *mUserServiceMockGetProfile) Expect(ctx context.Context, id string) *mUserServiceMockGetProfile {
	if mmGetProfile.mock.funcGetProfile != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Set")
	}

	if mmGetProfile.defaultExpectation == nil {
		mmGetProfile.defaultExpectation = &UserServiceMockGetProfileExpectation{}
	}

	if mmGetProfile.defaultExpectation.paramPtrs != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by ExpectParams functions")
	}

	mmGetProfile.defaultExpectation.params = &UserServiceMockGetProfileParams{ctx, id}
	mmGetProfile.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetProfile.expectations {
		if minimock.Equal(e.params, mmGetProfile.defaultExpectation.params) {
			mmGetProfile.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProfile.defaultExpectation.params)
		}
	}

	return mmGetProfile
}

// ExpectCtxParam1 sets up expected param ctx for UserService.GetProfile
func (mmGetProfile *mUserServiceMockGetProfile) ExpectCtxParam1(ctx context.Context) *mUserServiceMockGetProfile {
	if mmGetProfile.mock.funcGetProfile != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Set")
	}

	if mmGetProfile.defaultExpectation == nil {
		mmGetProfile.defaultExpectation = &UserServiceMockGetProfileExpectation{}
	}

	if mmGetProfile.defaultExpectation.params != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Expect")
	}

	if mmGetProfile.defaultExpectation.paramPtrs == nil {
		mmGetProfile.defaultExpectation.paramPtrs = &UserServiceMockGetProfileParamPtrs{}
	}
	mmGetProfile.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetProfile.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetProfile
}

// ExpectIdParam2 sets up expected param id for UserService.GetProfile
func (mmGetProfile *mUserServiceMockGetProfile) ExpectIdParam2(id string) *mUserServiceMockGetProfile {
	if mmGetProfile.mock.funcGetProfile != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Set")
	}

	if mmGetProfile.defaultExpectation == nil {
		mmGetProfile.defaultExpectation = &UserServiceMockGetProfileExpectation{}
	}

	if mmGetProfile.defaultExpectation.params != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Expect")
	}

	if mmGetProfile.defaultExpectation.paramPtrs == nil {
		mmGetProfile.defaultExpectation.paramPtrs = &UserServiceMockGetProfileParamPtrs{}
	}
	mmGetProfile.defaultExpectation.paramPtrs.id = &id
	mmGetProfile.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetProfile
}

// Inspect accepts an inspector function that has same arguments as the UserService.GetProfile
func (mmGetProfile *mUserServiceMockGetProfile) Inspect(f func(ctx context.Context, id string)) *mUserServiceMockGetProfile {
	if mmGetProfile.mock.inspectFuncGetProfile != nil {
		mmGetProfile.mock.t.Fatalf("Inspect function is already set for UserServiceMock.GetProfile")
	}

	mmGetProfile.mock.inspectFuncGetProfile = f

	return mmGetProfile
}

// Return sets up results that will be returned by UserService.GetProfile
func (mmGetProfile *mUserServiceMockGetProfile) Return(up1 *models.UserProfile, err error) *UserServiceMock {
	if mmGetProfile.mock.funcGetProfile != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Set")
	}

	if mmGetProfile.defaultExpectation == nil {
		mmGetProfile.defaultExpectation = &UserServiceMockGetProfileExpectation{mock: mmGetProfile.mock}
	}
	mmGetProfile.defaultExpectation.results = &UserServiceMockGetProfileResults{up1, err}
	mmGetProfile.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetProfile.mock
}

// Set uses given function f to mock the UserService.GetProfile method
func (mmGetProfile *mUserServiceMockGetProfile) Set(f func(ctx context.Context, id string) (up1 *models.UserProfile, err error)) *UserServiceMock {
	if mmGetProfile.defaultExpectation != nil {
		mmGetProfile.mock.t.Fatalf("Default expectation is already set for the UserService.GetProfile method")
	}

	if len(mmGetProfile.expectations) > 0 {
		mmGetProfile.mock.t.Fatalf("Some expectations are already set for the UserService.GetProfile method")
	}

	mmGetProfile.mock.funcGetProfile = f
	mmGetProfile.mock.funcGetProfileOrigin = minimock.CallerInfo(1)
	return mmGetProfile.mock
}

// When sets expectation for the UserService.GetProfile which will trigger the result defined by the following
// Then helper
func (mmGetProfile *mUserServiceMockGetProfile) When(ctx context.Context, id string) *UserServiceMockGetProfileExpectation {
	if mmGetProfile.mock.funcGetProfile != nil {
		mmGetProfile.mock.t.Fatalf("UserServiceMock.GetProfile mock is already set by Set")
	}

	expectation := &UserServiceMockGetProfileExpectation{
		mock:               mmGetProfile.mock,
		params:             &UserServiceMockGetProfileParams{ctx, id},
		expectationOrigins: UserServiceMockGetProfileExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetProfile.expectations = append(mmGetProfile.expectations, expectation)
	return expectation
}

// Then sets up UserService.GetProfile return parameters for the expectation previously defined by the When method
func (e *UserServiceMockGetProfileExpectation) Then(up1 *models.UserProfile, err error) *UserServiceMock {
	e.results = &UserServiceMockGetProfileResults{up1, err}
	return e.mock
}

// Times sets number of times UserService.GetProfile should be invoked
func (mmGetProfile *mUserServiceMockGetProfile) Times(n uint64) *mUserServiceMockGetProfile {
	if n == 0 {
		mmGetProfile.mock.t.Fatalf("Times of UserServiceMock.GetProfile mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProfile.expectedInvocations, n)
	mmGetProfile.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetProfile
}

func (mmGetProfile *mUserServiceMockGetProfile) invocationsDone() bool {
	if len(mmGetProfile.expectations) == 0 && mmGetProfile.defaultExpectation == nil && mmGetProfile.mock.funcGetProfile == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProfile.mock.afterGetProfileCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProfile.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProfile implements mm_service.UserService
func (mmGetProfile *UserServiceMock) GetProfile(ctx context.Context, id string) (up1 *models.UserProfile, err error) {
	mm_atomic.AddUint64(&mmGetProfile.beforeGetProfileCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProfile.afterGetProfileCounter, 1)

	mmGetProfile.t.Helper()

	if mmGetProfile.inspectFuncGetProfile != nil {
		mmGetProfile.inspectFuncGetProfile(ctx, id)
	}

	mm_params := UserServiceMockGetProfileParams{ctx, id}

	// Record call args
	mmGetProfile.GetProfileMock.mutex.Lock()
	mmGetProfile.GetProfileMock.callArgs = append(mmGetProfile.GetProfileMock.callArgs, &mm_params)
	mmGetProfile.GetProfileMock.mutex.Unlock()

	for _, e := range mmGetProfile.GetProfileMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetProfile.GetProfileMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProfile.GetProfileMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProfile.GetProfileMock.defaultExpectation.params
		mm_want_ptrs := mmGetProfile.GetProfileMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockGetProfileParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetProfile.t.Errorf("UserServiceMock.GetProfile got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProfile.GetProfileMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetProfile.t.Errorf("UserServiceMock.GetProfile got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProfile.GetProfileMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProfile.t.Errorf("UserServiceMock.GetProfile got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetProfile.GetProfileMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProfile.GetProfileMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProfile.t.Fatal("No results are set for the UserServiceMock.GetProfile")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetProfile.funcGetProfile != nil {
		return mmGetProfile.funcGetProfile(ctx, id)
	}
	mmGetProfile.t.Fatalf("Unexpected call to UserServiceMock.GetProfile. %v %v", ctx, id)
	return
}

// GetProfileAfterCounter returns a count of finished UserServiceMock.GetProfile invocations
func (mmGetProfile *UserServiceMock) GetProfileAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProfile.afterGetProfileCounter)
}

// GetProfileBeforeCounter returns a count of UserServiceMock.GetProfile invocations
func (mmGetProfile *UserServiceMock) GetProfileBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProfile.beforeGetProfileCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.GetProfile.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProfile *mUserServiceMockGetProfile) Calls() []*UserServiceMockGetProfileParams {
	mmGetProfile.mutex.RLock()

	argCopy := make([]*UserServiceMockGetProfileParams, len(mmGetProfile.callArgs))
	copy(argCopy, mmGetProfile.callArgs)

	mmGetProfile.mutex.RUnlock()

	return argCopy
}

// MinimockGetProfileDone returns true if the count of the GetProfile invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockGetProfileDone() bool {
	if m.GetProfileMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProfileMock.invocationsDone()
}

// MinimockGetProfileInspect logs each unmet expectation
func (m *UserServiceMock) MinimockGetProfileInspect() {
	for _, e := range m.GetProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.GetProfile at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetProfileCounter := mm_atomic.LoadUint64(&m.afterGetProfileCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProfileMock.defaultExpectation != nil && afterGetProfileCounter < 1 {
		if m.GetProfileMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.GetProfile at\n%s", m.GetProfileMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.GetProfile at\n%s with params: %#v", m.GetProfileMock.defaultExpectation.expectationOrigins.origin, *m.GetProfileMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProfile != nil && afterGetProfileCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.GetProfile at\n%s", m.funcGetProfileOrigin)
	}

	if !m.GetProfileMock.invocationsDone() && afterGetProfileCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.GetProfile at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetProfileMock.expectedInvocations), m.GetProfileMock.expectedInvocationsOrigin, afterGetProfileCounter)
	}
}

type mUserServiceMockLoginUser struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockLoginUserExpectation
	expectations       []*UserServiceMockLoginUserExpectation

	callArgs []*UserServiceMockLoginUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockLoginUserExpectation specifies expectation struct of the UserService.LoginUser
type UserServiceMockLoginUserExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockLoginUserParams
	paramPtrs          *UserServiceMockLoginUserParamPtrs
	expectationOrigins UserServiceMockLoginUserExpectationOrigins
	results            *UserServiceMockLoginUserResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockLoginUserParams contains parameters of the UserService.LoginUser
type UserServiceMockLoginUserParams struct {
	ctx context.Context
	req *models.LoginUserRequest
}

// UserServiceMockLoginUserParamPtrs contains pointers to parameters of the UserService.LoginUser
type UserServiceMockLoginUserParamPtrs struct {
	ctx *context.Context
	req **models.LoginUserRequest
}

// UserServiceMockLoginUserResults contains results of the UserService.LoginUser
type UserServiceMockLoginUserResults struct {
	s1  string
	err error
}

// UserServiceMockLoginUserOrigins contains origins of expectations of the UserService.LoginUser
type UserServiceMockLoginUserExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLoginUser *mUserServiceMockLoginUser) Optional() *mUserServiceMockLoginUser {
	mmLoginUser.optional = true
	return mmLoginUser
}

// Expect sets up expected params for UserService.LoginUser
func (mmLoginUser *mUserServiceMockLoginUser) Expect(ctx context.Context, req *models.LoginUserRequest) *mUserServiceMockLoginUser {
	if mmLoginUser.mock.funcLoginUser != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Set")
	}

	if mmLoginUser.defaultExpectation == nil {
		mmLoginUser.defaultExpectation = &UserServiceMockLoginUserExpectation{}
	}

	if mmLoginUser.defaultExpectation.paramPtrs != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by ExpectParams functions")
	}

	mmLoginUser.defaultExpectation.params = &UserServiceMockLoginUserParams{ctx, req}
	mmLoginUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLoginUser.expectations {
		if minimock.Equal(e.params, mmLoginUser.defaultExpectation.params) {
			mmLoginUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLoginUser.defaultExpectation.params)
		}
	}

	return mmLoginUser
}

// ExpectCtxParam1 sets up expected param ctx for UserService.LoginUser
func (mmLoginUser *mUserServiceMockLoginUser) ExpectCtxParam1(ctx context.Context) *mUserServiceMockLoginUser {
	if mmLoginUser.mock.funcLoginUser != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Set")
	}

	if mmLoginUser.defaultExpectation == nil {
		mmLoginUser.defaultExpectation = &UserServiceMockLoginUserExpectation{}
	}

	if mmLoginUser.defaultExpectation.params != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Expect")
	}

	if mmLoginUser.defaultExpectation.paramPtrs == nil {
		mmLoginUser.defaultExpectation.paramPtrs = &UserServiceMockLoginUserParamPtrs{}
	}
	mmLoginUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmLoginUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLoginUser
}

// ExpectReqParam2 sets up expected param req for UserService.LoginUser
func (mmLoginUser *mUserServiceMockLoginUser) ExpectReqParam2(req *models.LoginUserRequest) *mUserServiceMockLoginUser {
	if mmLoginUser.mock.funcLoginUser != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Set")
	}

	if mmLoginUser.defaultExpectation == nil {
		mmLoginUser.defaultExpectation = &UserServiceMockLoginUserExpectation{}
	}

	if mmLoginUser.defaultExpectation.params != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Expect")
	}

	if mmLoginUser.defaultExpectation.paramPtrs == nil {
		mmLoginUser.defaultExpectation.paramPtrs = &UserServiceMockLoginUserParamPtrs{}
	}
	mmLoginUser.defaultExpectation.paramPtrs.req = &req
	mmLoginUser.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmLoginUser
}

// Inspect accepts an inspector function that has same arguments as the UserService.LoginUser
func (mmLoginUser *mUserServiceMockLoginUser) Inspect(f func(ctx context.Context, req *models.LoginUserRequest)) *mUserServiceMockLoginUser {
	if mmLoginUser.mock.inspectFuncLoginUser != nil {
		mmLoginUser.mock.t.Fatalf("Inspect function is already set for UserServiceMock.LoginUser")
	}

	mmLoginUser.mock.inspectFuncLoginUser = f

	return mmLoginUser
}

// Return sets up results that will be returned by UserService.LoginUser
func (mmLoginUser *mUserServiceMockLoginUser) Return(s1 string, err error) *UserServiceMock {
	if mmLoginUser.mock.funcLoginUser != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Set")
	}

	if mmLoginUser.defaultExpectation == nil {
		mmLoginUser.defaultExpectation = &UserServiceMockLoginUserExpectation{mock: mmLoginUser.mock}
	}
	mmLoginUser.defaultExpectation.results = &UserServiceMockLoginUserResults{s1, err}
	mmLoginUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLoginUser.mock
}

// Set uses given function f to mock the UserService.LoginUser method
func (mmLoginUser *mUserServiceMockLoginUser) Set(f func(ctx context.Context, req *models.LoginUserRequest) (s1 string, err error)) *UserServiceMock {
	if mmLoginUser.defaultExpectation != nil {
		mmLoginUser.mock.t.Fatalf("Default expectation is already set for the UserService.LoginUser method")
	}

	if len(mmLoginUser.expectations) > 0 {
		mmLoginUser.mock.t.Fatalf("Some expectations are already set for the UserService.LoginUser method")
	}

	mmLoginUser.mock.funcLoginUser = f
	mmLoginUser.mock.funcLoginUserOrigin = minimock.CallerInfo(1)
	return mmLoginUser.mock
}

// When sets expectation for the UserService.LoginUser which will trigger the result defined by the following
// Then helper
func (mmLoginUser *mUserServiceMockLoginUser) When(ctx context.Context, req *models.LoginUserRequest) *UserServiceMockLoginUserExpectation {
	if mmLoginUser.mock.funcLoginUser != nil {
		mmLoginUser.mock.t.Fatalf("UserServiceMock.LoginUser mock is already set by Set")
	}

	expectation := &UserServiceMockLoginUserExpectation{
		mock:               mmLoginUser.mock,
		params:             &UserServiceMockLoginUserParams{ctx, req},
		expectationOrigins: UserServiceMockLoginUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLoginUser.expectations = append(mmLoginUser.expectations, expectation)
	return expectation
}

// Then sets up UserService.LoginUser return parameters for the expectation previously defined by the When method
func (e *UserServiceMockLoginUserExpectation) Then(s1 string, err error) *UserServiceMock {
	e.results = &UserServiceMockLoginUserResults{s1, err}
	return e.mock
}

// Times sets number of times UserService.LoginUser should be invoked
func (mmLoginUser *mUserServiceMockLoginUser) Times(n uint64) *mUserServiceMockLoginUser {
	if n == 0 {
		mmLoginUser.mock.t.Fatalf("Times of UserServiceMock.LoginUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLoginUser.expectedInvocations, n)
	mmLoginUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLoginUser
}

func (mmLoginUser *mUserServiceMockLoginUser) invocationsDone() bool {
	if len(mmLoginUser.expectations) == 0 && mmLoginUser.defaultExpectation == nil && mmLoginUser.mock.funcLoginUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLoginUser.mock.afterLoginUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLoginUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// LoginUser implements mm_service.UserService
func (mmLoginUser *UserServiceMock) LoginUser(ctx context.Context, req *models.LoginUserRequest) (s1 string, err error) {
	mm_atomic.AddUint64(&mmLoginUser.beforeLoginUserCounter, 1)
	defer mm_atomic.AddUint64(&mmLoginUser.afterLoginUserCounter, 1)

	mmLoginUser.t.Helper()

	if mmLoginUser.inspectFuncLoginUser != nil {
		mmLoginUser.inspectFuncLoginUser(ctx, req)
	}

	mm_params := UserServiceMockLoginUserParams{ctx, req}

	// Record call args
	mmLoginUser.LoginUserMock.mutex.Lock()
	mmLoginUser.LoginUserMock.callArgs = append(mmLoginUser.LoginUserMock.callArgs, &mm_params)
	mmLoginUser.LoginUserMock.mutex.Unlock()

	for _, e := range mmLoginUser.LoginUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmLoginUser.LoginUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLoginUser.LoginUserMock.defaultExpectation.Counter, 1)
		mm_want := mmLoginUser.LoginUserMock.defaultExpectation.params
		mm_want_ptrs := mmLoginUser.LoginUserMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockLoginUserParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLoginUser.t.Errorf("UserServiceMock.LoginUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLoginUser.LoginUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmLoginUser.t.Errorf("UserServiceMock.LoginUser got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLoginUser.LoginUserMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLoginUser.t.Errorf("UserServiceMock.LoginUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLoginUser.LoginUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLoginUser.LoginUserMock.defaultExpectation.results
		if mm_results == nil {
			mmLoginUser.t.Fatal("No results are set for the UserServiceMock.LoginUser")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmLoginUser.funcLoginUser != nil {
		return mmLoginUser.funcLoginUser(ctx, req)
	}
	mmLoginUser.t.Fatalf("Unexpected call to UserServiceMock.LoginUser. %v %v", ctx, req)
	return
}

// LoginUserAfterCounter returns a count of finished UserServiceMock.LoginUser invocations
func (mmLoginUser *UserServiceMock) LoginUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLoginUser.afterLoginUserCounter)
}

// LoginUserBeforeCounter returns a count of UserServiceMock.LoginUser invocations
func (mmLoginUser *UserServiceMock) LoginUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLoginUser.beforeLoginUserCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.LoginUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLoginUser *mUserServiceMockLoginUser) Calls() []*UserServiceMockLoginUserParams {
	mmLoginUser.mutex.RLock()

	argCopy := make([]*UserServiceMockLoginUserParams, len(mmLoginUser.callArgs))
	copy(argCopy, mmLoginUser.callArgs)

	mmLoginUser.mutex.RUnlock()

	return argCopy
}

// MinimockLoginUserDone returns true if the count of the LoginUser invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockLoginUserDone() bool {
	if m.LoginUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LoginUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LoginUserMock.invocationsDone()
}

// MinimockLoginUserInspect logs each unmet expectation
func (m *UserServiceMock) MinimockLoginUserInspect() {
	for _, e := range m.LoginUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.LoginUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLoginUserCounter := mm_atomic.LoadUint64(&m.afterLoginUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LoginUserMock.defaultExpectation != nil && afterLoginUserCounter < 1 {
		if m.LoginUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.LoginUser at\n%s", m.LoginUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.LoginUser at\n%s with params: %#v", m.LoginUserMock.defaultExpectation.expectationOrigins.origin, *m.LoginUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLoginUser != nil && afterLoginUserCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.LoginUser at\n%s", m.funcLoginUserOrigin)
	}

	if !m.LoginUserMock.invocationsDone() && afterLoginUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.LoginUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LoginUserMock.expectedInvocations), m.LoginUserMock.expectedInvocationsOrigin, afterLoginUserCounter)
	}
}

type mUserServiceMockRegisterUser struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockRegisterUserExpectation
	expectations       []*UserServiceMockRegisterUserExpectation

	callArgs []*UserServiceMockRegisterUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockRegisterUserExpectation specifies expectation struct of the UserService.RegisterUser
type UserServiceMockRegisterUserExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockRegisterUserParams
	paramPtrs          *UserServiceMockRegisterUserParamPtrs
	expectationOrigins UserServiceMockRegisterUserExpectationOrigins
	results            *UserServiceMockRegisterUserResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockRegisterUserParams contains parameters of the UserService.RegisterUser
type UserServiceMockRegisterUserParams struct {
	ctx context.Context
	req *models.RegisterRequest
}

// UserServiceMockRegisterUserParamPtrs contains pointers to parameters of the UserService.RegisterUser
type UserServiceMockRegisterUserParamPtrs struct {
	ctx *context.Context
	req **models.RegisterRequest
}

// UserServiceMockRegisterUserResults contains results of the UserService.RegisterUser
type UserServiceMockRegisterUserResults struct {
	s1  string
	err error
}

// UserServiceMockRegisterUserOrigins contains origins of expectations of the UserService.RegisterUser
type UserServiceMockRegisterUserExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRegisterUser *mUserServiceMockRegisterUser) Optional() *mUserServiceMockRegisterUser {
	mmRegisterUser.optional = true
	return mmRegisterUser
}

// Expect sets up expected params for UserService.RegisterUser
func (mmRegisterUser *mUserServiceMockRegisterUser) Expect(ctx context.Context, req *models.RegisterRequest) *mUserServiceMockRegisterUser {
	if mmRegisterUser.mock.funcRegisterUser != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Set")
	}

	if mmRegisterUser.defaultExpectation == nil {
		mmRegisterUser.defaultExpectation = &UserServiceMockRegisterUserExpectation{}
	}

	if mmRegisterUser.defaultExpectation.paramPtrs != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by ExpectParams functions")
	}

	mmRegisterUser.defaultExpectation.params = &UserServiceMockRegisterUserParams{ctx, req}
	mmRegisterUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRegisterUser.expectations {
		if minimock.Equal(e.params, mmRegisterUser.defaultExpectation.params) {
			mmRegisterUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRegisterUser.defaultExpectation.params)
		}
	}

	return mmRegisterUser
}

// ExpectCtxParam1 sets up expected param ctx for UserService.RegisterUser
func (mmRegisterUser *mUserServiceMockRegisterUser) ExpectCtxParam1(ctx context.Context) *mUserServiceMockRegisterUser {
	if mmRegisterUser.mock.funcRegisterUser != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Set")
	}

	if mmRegisterUser.defaultExpectation == nil {
		mmRegisterUser.defaultExpectation = &UserServiceMockRegisterUserExpectation{}
	}

	if mmRegisterUser.defaultExpectation.params != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Expect")
	}

	if mmRegisterUser.defaultExpectation.paramPtrs == nil {
		mmRegisterUser.defaultExpectation.paramPtrs = &UserServiceMockRegisterUserParamPtrs{}
	}
	mmRegisterUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmRegisterUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRegisterUser
}

// ExpectReqParam2 sets up expected param req for UserService.RegisterUser
func (mmRegisterUser *mUserServiceMockRegisterUser) ExpectReqParam2(req *models.RegisterRequest) *mUserServiceMockRegisterUser {
	if mmRegisterUser.mock.funcRegisterUser != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Set")
	}

	if mmRegisterUser.defaultExpectation == nil {
		mmRegisterUser.defaultExpectation = &UserServiceMockRegisterUserExpectation{}
	}

	if mmRegisterUser.defaultExpectation.params != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Expect")
	}

	if mmRegisterUser.defaultExpectation.paramPtrs == nil {
		mmRegisterUser.defaultExpectation.paramPtrs = &UserServiceMockRegisterUserParamPtrs{}
	}
	mmRegisterUser.defaultExpectation.paramPtrs.req = &req
	mmRegisterUser.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmRegisterUser
}

// Inspect accepts an inspector function that has same arguments as the UserService.RegisterUser
func (mmRegisterUser *mUserServiceMockRegisterUser) Inspect(f func(ctx context.Context, req *models.RegisterRequest)) *mUserServiceMockRegisterUser {
	if mmRegisterUser.mock.inspectFuncRegisterUser != nil {
		mmRegisterUser.mock.t.Fatalf("Inspect function is already set for UserServiceMock.RegisterUser")
	}

	mmRegisterUser.mock.inspectFuncRegisterUser = f

	return mmRegisterUser
}

// Return sets up results that will be returned by UserService.RegisterUser
func (mmRegisterUser *mUserServiceMockRegisterUser) Return(s1 string, err error) *UserServiceMock {
	if mmRegisterUser.mock.funcRegisterUser != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Set")
	}

	if mmRegisterUser.defaultExpectation == nil {
		mmRegisterUser.defaultExpectation = &UserServiceMockRegisterUserExpectation{mock: mmRegisterUser.mock}
	}
	mmRegisterUser.defaultExpectation.results = &UserServiceMockRegisterUserResults{s1, err}
	mmRegisterUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRegisterUser.mock
}

// Set uses given function f to mock the UserService.RegisterUser method
func (mmRegisterUser *mUserServiceMockRegisterUser) Set(f func(ctx context.Context, req *models.RegisterRequest) (s1 string, err error)) *UserServiceMock {
	if mmRegisterUser.defaultExpectation != nil {
		mmRegisterUser.mock.t.Fatalf("Default expectation is already set for the UserService.RegisterUser method")
	}

	if len(mmRegisterUser.expectations) > 0 {
		mmRegisterUser.mock.t.Fatalf("Some expectations are already set for the UserService.RegisterUser method")
	}

	mmRegisterUser.mock.funcRegisterUser = f
	mmRegisterUser.mock.funcRegisterUserOrigin = minimock.CallerInfo(1)
	return mmRegisterUser.mock
}

// When sets expectation for the UserService.RegisterUser which will trigger the result defined by the following
// Then helper
func (mmRegisterUser *mUserServiceMockRegisterUser) When(ctx context.Context, req *models.RegisterRequest) *UserServiceMockRegisterUserExpectation {
	if mmRegisterUser.mock.funcRegisterUser != nil {
		mmRegisterUser.mock.t.Fatalf("UserServiceMock.RegisterUser mock is already set by Set")
	}

	expectation := &UserServiceMockRegisterUserExpectation{
		mock:               mmRegisterUser.mock,
		params:             &UserServiceMockRegisterUserParams{ctx, req},
		expectationOrigins: UserServiceMockRegisterUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRegisterUser.expectations = append(mmRegisterUser.expectations, expectation)
	return expectation
}

// Then sets up UserService.RegisterUser return parameters for the expectation previously defined by the When method
func (e *UserServiceMockRegisterUserExpectation) Then(s1 string, err error) *UserServiceMock {
	e.results = &UserServiceMockRegisterUserResults{s1, err}
	return e.mock
}

// Times sets number of times UserService.RegisterUser should be invoked
func (mmRegisterUser *mUserServiceMockRegisterUser) Times(n uint64) *mUserServiceMockRegisterUser {
	if n == 0 {
		mmRegisterUser.mock.t.Fatalf("Times of UserServiceMock.RegisterUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRegisterUser.expectedInvocations, n)
	mmRegisterUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRegisterUser
}

func (mmRegisterUser *mUserServiceMockRegisterUser) invocationsDone() bool {
	if len(mmRegisterUser.expectations) == 0 && mmRegisterUser.defaultExpectation == nil && mmRegisterUser.mock.funcRegisterUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRegisterUser.mock.afterRegisterUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRegisterUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RegisterUser implements mm_service.UserService
func (mmRegisterUser *UserServiceMock) RegisterUser(ctx context.Context, req *models.RegisterRequest) (s1 string, err error) {
	mm_atomic.AddUint64(&mmRegisterUser.beforeRegisterUserCounter, 1)
	defer mm_atomic.AddUint64(&mmRegisterUser.afterRegisterUserCounter, 1)

	mmRegisterUser.t.Helper()

	if mmRegisterUser.inspectFuncRegisterUser != nil {
		mmRegisterUser.inspectFuncRegisterUser(ctx, req)
	}

	mm_params := UserServiceMockRegisterUserParams{ctx, req}

	// Record call args
	mmRegisterUser.RegisterUserMock.mutex.Lock()
	mmRegisterUser.RegisterUserMock.callArgs = append(mmRegisterUser.RegisterUserMock.callArgs, &mm_params)
	mmRegisterUser.RegisterUserMock.mutex.Unlock()

	for _, e := range mmRegisterUser.RegisterUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmRegisterUser.RegisterUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRegisterUser.RegisterUserMock.defaultExpectation.Counter, 1)
		mm_want := mmRegisterUser.RegisterUserMock.defaultExpectation.params
		mm_want_ptrs := mmRegisterUser.RegisterUserMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockRegisterUserParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRegisterUser.t.Errorf("UserServiceMock.RegisterUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegisterUser.RegisterUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmRegisterUser.t.Errorf("UserServiceMock.RegisterUser got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegisterUser.RegisterUserMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRegisterUser.t.Errorf("UserServiceMock.RegisterUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRegisterUser.RegisterUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRegisterUser.RegisterUserMock.defaultExpectation.results
		if mm_results == nil {
			mmRegisterUser.t.Fatal("No results are set for the UserServiceMock.RegisterUser")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmRegisterUser.funcRegisterUser != nil {
		return mmRegisterUser.funcRegisterUser(ctx, req)
	}
	mmRegisterUser.t.Fatalf("Unexpected call to UserServiceMock.RegisterUser. %v %v", ctx, req)
	return
}

// RegisterUserAfterCounter returns a count of finished UserServiceMock.RegisterUser invocations
func (mmRegisterUser *UserServiceMock) RegisterUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegisterUser.afterRegisterUserCounter)
}

// RegisterUserBeforeCounter returns a count of UserServiceMock.RegisterUser invocations
func (mmRegisterUser *UserServiceMock) RegisterUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegisterUser.beforeRegisterUserCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.RegisterUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRegisterUser *mUserServiceMockRegisterUser) Calls() []*UserServiceMockRegisterUserParams {
	mmRegisterUser.mutex.RLock()

	argCopy := make([]*UserServiceMockRegisterUserParams, len(mmRegisterUser.callArgs))
	copy(argCopy, mmRegisterUser.callArgs)

	mmRegisterUser.mutex.RUnlock()

	return argCopy
}

// MinimockRegisterUserDone returns true if the count of the RegisterUser invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockRegisterUserDone() bool {
	if m.RegisterUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RegisterUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RegisterUserMock.invocationsDone()
}

// MinimockRegisterUserInspect logs each unmet expectation
func (m *UserServiceMock) MinimockRegisterUserInspect() {
	for _, e := range m.RegisterUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.RegisterUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRegisterUserCounter := mm_atomic.LoadUint64(&m.afterRegisterUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RegisterUserMock.defaultExpectation != nil && afterRegisterUserCounter < 1 {
		if m.RegisterUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.RegisterUser at\n%s", m.RegisterUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.RegisterUser at\n%s with params: %#v", m.RegisterUserMock.defaultExpectation.expectationOrigins.origin, *m.RegisterUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRegisterUser != nil && afterRegisterUserCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.RegisterUser at\n%s", m.funcRegisterUserOrigin)
	}

	if !m.RegisterUserMock.invocationsDone() && afterRegisterUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.RegisterUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RegisterUserMock.expectedInvocations), m.RegisterUserMock.expectedInvocationsOrigin, afterRegisterUserCounter)
	}
}

type mUserServiceMockUpdateProfile struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockUpdateProfileExpectation
	expectations       []*UserServiceMockUpdateProfileExpectation

	callArgs []*UserServiceMockUpdateProfileParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockUpdateProfileExpectation specifies expectation struct of the UserService.UpdateProfile
type UserServiceMockUpdateProfileExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockUpdateProfileParams
	paramPtrs          *UserServiceMockUpdateProfileParamPtrs
	expectationOrigins UserServiceMockUpdateProfileExpectationOrigins
	results            *UserServiceMockUpdateProfileResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockUpdateProfileParams contains parameters of the UserService.UpdateProfile
type UserServiceMockUpdateProfileParams struct {
	ctx context.Context
	req *models.UpdateProfileRequest
}

// UserServiceMockUpdateProfileParamPtrs contains pointers to parameters of the UserService.UpdateProfile
type UserServiceMockUpdateProfileParamPtrs struct {
	ctx *context.Context
	req **models.UpdateProfileRequest
}

// UserServiceMockUpdateProfileResults contains results of the UserService.UpdateProfile
type UserServiceMockUpdateProfileResults struct {
	err error
}

// UserServiceMockUpdateProfileOrigins contains origins of expectations of the UserService.UpdateProfile
type UserServiceMockUpdateProfileExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Optional() *mUserServiceMockUpdateProfile {
	mmUpdateProfile.optional = true
	return mmUpdateProfile
}

// Expect sets up expected params for UserService.UpdateProfile
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Expect(ctx context.Context, req *models.UpdateProfileRequest) *mUserServiceMockUpdateProfile {
	if mmUpdateProfile.mock.funcUpdateProfile != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Set")
	}

	if mmUpdateProfile.defaultExpectation == nil {
		mmUpdateProfile.defaultExpectation = &UserServiceMockUpdateProfileExpectation{}
	}

	if mmUpdateProfile.defaultExpectation.paramPtrs != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by ExpectParams functions")
	}

	mmUpdateProfile.defaultExpectation.params = &UserServiceMockUpdateProfileParams{ctx, req}
	mmUpdateProfile.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateProfile.expectations {
		if minimock.Equal(e.params, mmUpdateProfile.defaultExpectation.params) {
			mmUpdateProfile.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateProfile.defaultExpectation.params)
		}
	}

	return mmUpdateProfile
}

// ExpectCtxParam1 sets up expected param ctx for UserService.UpdateProfile
func (mmUpdateProfile *mUserServiceMockUpdateProfile) ExpectCtxParam1(ctx context.Context) *mUserServiceMockUpdateProfile {
	if mmUpdateProfile.mock.funcUpdateProfile != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Set")
	}

	if mmUpdateProfile.defaultExpectation == nil {
		mmUpdateProfile.defaultExpectation = &UserServiceMockUpdateProfileExpectation{}
	}

	if mmUpdateProfile.defaultExpectation.params != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Expect")
	}

	if mmUpdateProfile.defaultExpectation.paramPtrs == nil {
		mmUpdateProfile.defaultExpectation.paramPtrs = &UserServiceMockUpdateProfileParamPtrs{}
	}
	mmUpdateProfile.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateProfile.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateProfile
}

// ExpectReqParam2 sets up expected param req for UserService.UpdateProfile
func (mmUpdateProfile *mUserServiceMockUpdateProfile) ExpectReqParam2(req *models.UpdateProfileRequest) *mUserServiceMockUpdateProfile {
	if mmUpdateProfile.mock.funcUpdateProfile != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Set")
	}

	if mmUpdateProfile.defaultExpectation == nil {
		mmUpdateProfile.defaultExpectation = &UserServiceMockUpdateProfileExpectation{}
	}

	if mmUpdateProfile.defaultExpectation.params != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Expect")
	}

	if mmUpdateProfile.defaultExpectation.paramPtrs == nil {
		mmUpdateProfile.defaultExpectation.paramPtrs = &UserServiceMockUpdateProfileParamPtrs{}
	}
	mmUpdateProfile.defaultExpectation.paramPtrs.req = &req
	mmUpdateProfile.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmUpdateProfile
}

// Inspect accepts an inspector function that has same arguments as the UserService.UpdateProfile
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Inspect(f func(ctx context.Context, req *models.UpdateProfileRequest)) *mUserServiceMockUpdateProfile {
	if mmUpdateProfile.mock.inspectFuncUpdateProfile != nil {
		mmUpdateProfile.mock.t.Fatalf("Inspect function is already set for UserServiceMock.UpdateProfile")
	}

	mmUpdateProfile.mock.inspectFuncUpdateProfile = f

	return mmUpdateProfile
}

// Return sets up results that will be returned by UserService.UpdateProfile
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Return(err error) *UserServiceMock {
	if mmUpdateProfile.mock.funcUpdateProfile != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Set")
	}

	if mmUpdateProfile.defaultExpectation == nil {
		mmUpdateProfile.defaultExpectation = &UserServiceMockUpdateProfileExpectation{mock: mmUpdateProfile.mock}
	}
	mmUpdateProfile.defaultExpectation.results = &UserServiceMockUpdateProfileResults{err}
	mmUpdateProfile.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateProfile.mock
}

// Set uses given function f to mock the UserService.UpdateProfile method
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Set(f func(ctx context.Context, req *models.UpdateProfileRequest) (err error)) *UserServiceMock {
	if mmUpdateProfile.defaultExpectation != nil {
		mmUpdateProfile.mock.t.Fatalf("Default expectation is already set for the UserService.UpdateProfile method")
	}

	if len(mmUpdateProfile.expectations) > 0 {
		mmUpdateProfile.mock.t.Fatalf("Some expectations are already set for the UserService.UpdateProfile method")
	}

	mmUpdateProfile.mock.funcUpdateProfile = f
	mmUpdateProfile.mock.funcUpdateProfileOrigin = minimock.CallerInfo(1)
	return mmUpdateProfile.mock
}

// When sets expectation for the UserService.UpdateProfile which will trigger the result defined by the following
// Then helper
func (mmUpdateProfile *mUserServiceMockUpdateProfile) When(ctx context.Context, req *models.UpdateProfileRequest) *UserServiceMockUpdateProfileExpectation {
	if mmUpdateProfile.mock.funcUpdateProfile != nil {
		mmUpdateProfile.mock.t.Fatalf("UserServiceMock.UpdateProfile mock is already set by Set")
	}

	expectation := &UserServiceMockUpdateProfileExpectation{
		mock:               mmUpdateProfile.mock,
		params:             &UserServiceMockUpdateProfileParams{ctx, req},
		expectationOrigins: UserServiceMockUpdateProfileExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateProfile.expectations = append(mmUpdateProfile.expectations, expectation)
	return expectation
}

// Then sets up UserService.UpdateProfile return parameters for the expectation previously defined by the When method
func (e *UserServiceMockUpdateProfileExpectation) Then(err error) *UserServiceMock {
	e.results = &UserServiceMockUpdateProfileResults{err}
	return e.mock
}

// Times sets number of times UserService.UpdateProfile should be invoked
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Times(n uint64) *mUserServiceMockUpdateProfile {
	if n == 0 {
		mmUpdateProfile.mock.t.Fatalf("Times of UserServiceMock.UpdateProfile mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateProfile.expectedInvocations, n)
	mmUpdateProfile.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateProfile
}

func (mmUpdateProfile *mUserServiceMockUpdateProfile) invocationsDone() bool {
	if len(mmUpdateProfile.expectations) == 0 && mmUpdateProfile.defaultExpectation == nil && mmUpdateProfile.mock.funcUpdateProfile == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateProfile.mock.afterUpdateProfileCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateProfile.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateProfile implements mm_service.UserService
func (mmUpdateProfile *UserServiceMock) UpdateProfile(ctx context.Context, req *models.UpdateProfileRequest) (err error) {
	mm_atomic.AddUint64(&mmUpdateProfile.beforeUpdateProfileCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateProfile.afterUpdateProfileCounter, 1)

	mmUpdateProfile.t.Helper()

	if mmUpdateProfile.inspectFuncUpdateProfile != nil {
		mmUpdateProfile.inspectFuncUpdateProfile(ctx, req)
	}

	mm_params := UserServiceMockUpdateProfileParams{ctx, req}

	// Record call args
	mmUpdateProfile.UpdateProfileMock.mutex.Lock()
	mmUpdateProfile.UpdateProfileMock.callArgs = append(mmUpdateProfile.UpdateProfileMock.callArgs, &mm_params)
	mmUpdateProfile.UpdateProfileMock.mutex.Unlock()

	for _, e := range mmUpdateProfile.UpdateProfileMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateProfile.UpdateProfileMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateProfile.UpdateProfileMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateProfile.UpdateProfileMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateProfile.UpdateProfileMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockUpdateProfileParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateProfile.t.Errorf("UserServiceMock.UpdateProfile got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateProfile.UpdateProfileMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmUpdateProfile.t.Errorf("UserServiceMock.UpdateProfile got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateProfile.UpdateProfileMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateProfile.t.Errorf("UserServiceMock.UpdateProfile got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateProfile.UpdateProfileMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateProfile.UpdateProfileMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateProfile.t.Fatal("No results are set for the UserServiceMock.UpdateProfile")
		}
		return (*mm_results).err
	}
	if mmUpdateProfile.funcUpdateProfile != nil {
		return mmUpdateProfile.funcUpdateProfile(ctx, req)
	}
	mmUpdateProfile.t.Fatalf("Unexpected call to UserServiceMock.UpdateProfile. %v %v", ctx, req)
	return
}

// UpdateProfileAfterCounter returns a count of finished UserServiceMock.UpdateProfile invocations
func (mmUpdateProfile *UserServiceMock) UpdateProfileAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateProfile.afterUpdateProfileCounter)
}

// UpdateProfileBeforeCounter returns a count of UserServiceMock.UpdateProfile invocations
func (mmUpdateProfile *UserServiceMock) UpdateProfileBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateProfile.beforeUpdateProfileCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.UpdateProfile.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateProfile *mUserServiceMockUpdateProfile) Calls() []*UserServiceMockUpdateProfileParams {
	mmUpdateProfile.mutex.RLock()

	argCopy := make([]*UserServiceMockUpdateProfileParams, len(mmUpdateProfile.callArgs))
	copy(argCopy, mmUpdateProfile.callArgs)

	mmUpdateProfile.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateProfileDone returns true if the count of the UpdateProfile invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockUpdateProfileDone() bool {
	if m.UpdateProfileMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateProfileMock.invocationsDone()
}

// MinimockUpdateProfileInspect logs each unmet expectation
func (m *UserServiceMock) MinimockUpdateProfileInspect() {
	for _, e := range m.UpdateProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.UpdateProfile at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateProfileCounter := mm_atomic.LoadUint64(&m.afterUpdateProfileCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateProfileMock.defaultExpectation != nil && afterUpdateProfileCounter < 1 {
		if m.UpdateProfileMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.UpdateProfile at\n%s", m.UpdateProfileMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.UpdateProfile at\n%s with params: %#v", m.UpdateProfileMock.defaultExpectation.expectationOrigins.origin, *m.UpdateProfileMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateProfile != nil && afterUpdateProfileCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.UpdateProfile at\n%s", m.funcUpdateProfileOrigin)
	}

	if !m.UpdateProfileMock.invocationsDone() && afterUpdateProfileCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.UpdateProfile at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateProfileMock.expectedInvocations), m.UpdateProfileMock.expectedInvocationsOrigin, afterUpdateProfileCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteProfileInspect()

			m.MinimockGetProfileInspect()

			m.MinimockLoginUserInspect()

			m.MinimockRegisterUserInspect()

			m.MinimockUpdateProfileInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteProfileDone() &&
		m.MinimockGetProfileDone() &&
		m.MinimockLoginUserDone() &&
		m.MinimockRegisterUserDone() &&
		m.MinimockUpdateProfileDone()
}
